In [130]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [131]:
df = pd.read_csv('../data/train.csv')
test = pd.read_csv('../data/test.csv')

In [132]:
df.head() 

# we have a passengerld column we can know the person's group or not split the column into two and take the number of group and deleted  
# we have cabin column we can split it into three columns (Deck,Num,Side) and we can do to_dumies for the deck and side and we can drop the num column because it is not important
# we have (Home planet,Destination) it need to to_dumies
# we have (cryo sleep,VIP,Transported) it is boolean we can change it to 0 and 1

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [133]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB

In [134]:
df.isnull().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [135]:
# we can fill the missing value in column Age by meadin()
# we can fill the missing value in column Cabin by fillna('Unknown/0/U')
# we can fill the missing value in column Home planet by fillna('Unknown')
# we can fill the missing value in colmn VIP by fillna(False)
# we can fill the missing value in column Destination by fillna('Unknown')
# we can fill the missing value in column Cryo sleep by fillna(False)
# we can fill the missing value in column spending by fillna(0)
# the column name drop

In [136]:
df[['Group', 'Group_num']] = df['PassengerId'].str.split('_', expand=True)

df['Group'] = df['Group'].astype(int)
df['Group_num'] = df['Group_num'].astype(int)

# Create Group_size feature
df['Group_size'] = df.groupby('Group')['Group'].transform('count')

# Create Is_alone feature
df['Is_alone'] = (df['Group_size'] == 1).astype(int)

# Drop original PassengerId
df.drop(columns=['PassengerId','Name'], inplace=True)

In [137]:
df.head()

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,Group,Group_num,Group_size,Is_alone
0,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,False,1,1,1,1
1,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,True,2,1,1,1
2,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False,3,1,2,0
3,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False,3,2,2,0
4,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,True,4,1,1,1

In [138]:
df['Cabin'] = df['Cabin'].fillna('Unknown/0/U')
df[['Deck', 'Num', 'Side']] = df['Cabin'].str.split('/', expand=True)
df.drop(columns=['Cabin'], inplace=True)
df['Num'] = pd.to_numeric(df['Num'], errors='coerce')

In [139]:
df.head()

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,Group,Group_num,Group_size,Is_alone,Deck,Num,Side
0,Europa,False,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,False,1,1,1,1,B,0,P
1,Earth,False,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,True,2,1,1,1,F,0,S
2,Europa,False,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False,3,1,2,0,A,0,S
3,Europa,False,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False,3,2,2,0,A,0,S
4,Earth,False,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,True,4,1,1,1,F,1,S

In [140]:
df['Num_bin'] = pd.qcut(df['Num'], q=4, duplicates='drop')

In [141]:
df['Num_bin'].value_counts()

Num_bin
(152.0, 407.0]     2176
(-0.001, 152.0]    2174
(983.0, 1894.0]    2173
(407.0, 983.0]     2170
Name: count, dtype: int64

In [142]:
df['HomePlanet'] = df['HomePlanet'].fillna('Unknown')
df['Destination'] = df['Destination'].fillna('Unknown')

In [151]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

cat_cols = ['HomePlanet', 'Destination', 'Deck', 'Side', 'Num_bin']

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)
    ],
    remainder='passthrough'
)
print(preprocessor.fit_transform(df).shape)

(8693, 38)

In [148]:
# RoomService                      181
# FoodCourt                        183
# ShoppingMall                     208
# Spa                              183
# VRDeck                           188

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,Group,Group_num,Group_size,Is_alone,Deck,Num,Side,Num_bin
0,Europa,False,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,False,1,1,1,1,B,0,P,"(-0.001, 152.0]"
1,Earth,False,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,True,2,1,1,1,F,0,S,"(-0.001, 152.0]"
2,Europa,False,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False,3,1,2,0,A,0,S,"(-0.001, 152.0]"
3,Europa,False,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False,3,2,2,0,A,0,S,"(-0.001, 152.0]"
4,Earth,False,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,True,4,1,1,1,F,1,S,"(-0.001, 152.0]"

In [167]:

df[['CryoSleep','VIP','Transported']] = df[['CryoSleep','VIP','Transported']].fillna(False)
df['Age'] = df['Age'].fillna(df['Age'].median())

In [168]:
df.isnull().sum()

HomePlanet                         0
CryoSleep                          0
Destination                        0
Age                                0
VIP                                0
RoomService                      181
FoodCourt                        183
ShoppingMall                     208
Spa                              183
VRDeck                           188
Transported                        0
Group                              0
Group_num                          0
Group_size                         0
Is_alone                           0
Deck                               0
Num                                0
Side                               0
Num_bin                            0
(CryoSleep, VIP, Transported)      0
dtype: int64

In [169]:
cols = ['RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']

df[cols] = df[cols].fillna(0)

In [170]:
df['Total_spending'] = df[cols].sum(axis=1)

In [171]:
df.isnull().sum()

HomePlanet                       0
CryoSleep                        0
Destination                      0
Age                              0
VIP                              0
RoomService                      0
FoodCourt                        0
ShoppingMall                     0
Spa                              0
VRDeck                           0
Transported                      0
Group                            0
Group_num                        0
Group_size                       0
Is_alone                         0
Deck                             0
Num                              0
Side                             0
Num_bin                          0
(CryoSleep, VIP, Transported)    0
Total_spending                   0
dtype: int64

In [ ]:
def preprocess_data(df):
    
    # PassengerId
    df[['Group', 'Group_Num']] = df['PassengerId'].str.split('_', expand=True)
    df['Group'] = df['Group'].astype(int)
    df['Group_Num'] = df['Group_Num'].astype(int)
    
    df['Group_size'] = df.groupby('Group')['Group'].transform('count')
    df['is_alone'] = (df['Group_size'] == 1).astype(int)
    
    df.drop(columns=['PassengerId','Name'], inplace=True)
    
    # Cabin
    df['Cabin'] = df['Cabin'].fillna('Unknown/0/U')
    df[['Deck', 'Num', 'Side']] = df['Cabin'].str.split('/', expand=True)
    df.drop(columns=['Cabin'], inplace=True)
    
    df['Num'] = pd.to_numeric(df['Num'], errors='coerce')
    df['Num_bin'] = pd.qcut(df['Num'], q=4, duplicates='drop')
    
    # Categorical missing
    df['HomePlanet'] = df['HomePlanet'].fillna('Unknown')
    df['Destination'] = df['Destination'].fillna('Unknown')
    
    # Boolean
    df[['CryoSleep','VIP']] = df[['CryoSleep','VIP']].fillna(False)
    df['CryoSleep'] = df['CryoSleep'].astype(int)
    df['VIP'] = df['VIP'].astype(int)
    
    # Age
    df['Age'] = df['Age'].fillna(df['Age'].median())
    
    # Spending
    cols = ['RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']
    df[cols] = df[cols].fillna(0)
    
    df['Total_spending'] = df[cols].sum(axis=1)
    df['No_spending'] = (df['Total_spending'] == 0).astype(int)
    
    return df

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
    
def preprocess_data(df):
    """
    the perprocessing steps for the data
    Parameters:
        df (pd.DataFrame): the data frame that we want to preprocess
    Returns:
        pd.DataFrame: the preprocessed data frame
    """
    # split the columns
    df[['Group', 'Group_Num']] = df['PassengerId'].str.split('_', expand=True)
    # convet to int
    df['Group'] = df['Group'].astype(int)
    df['Group_Num'] = df['Group_Num'].astype(int)  
    
    # Create Group_size feature
    df['Group_size'] = df.groupby('Group')['Group'].transform('count')
 
    
    # create new columns for is_alone
    df['is_alone'] = df['Group']==1
    
    # drop the Name and PassengerId column
    df.drop(columns=['PassengerId','Name'], inplace=True)
    
    # fill null by ('unknown/0/U') and split the cabin column into three columns (Deck,Num,Side) and drop the cabin column and convert the num column to numeric and create new column for num_bin by using qcut
    df['Cabin'] = df['Cabin'].fillna('Unknown/0/U')
    # split the data 
    df[['Deck', 'Num', 'Side']] = df['Cabin'].str.split('/', expand=True)
    # drop the cabin column
    df.drop(columns=['Cabin'], inplace=True)
    # convert the num column to numeric
    df['Num'] = pd.to_numeric(df['Num'], errors='coerce')
    # create new column for num_bin by using qcut and make in 4 group 
    df['Num_bin'] = pd.qcut(df['Num'], q=4, duplicates='drop')
        
    
    # cabin column we can fill the missing value by ('unknown/0/U') and split the cabin column into three columns (Deck,Num,Side) and drop the cabin column and convert the num column to numeric and create new column for num_bin by using qcut
    df['Cabin'] = df['Cabin'].fillna('Unknown/0/U')
    df['Destination'] = df['Destination'].fillna('Unknown')
    
    # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    cat_cols = ['HomePlanet', 'Destination', 'Deck', 'Side', 'Num_bin']
    
    preprocessor = ColumnTransformer(
        transformers=[
            ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)
        ],
        remainder='passthrough'
    )
    print(preprocessor.fit_transform(df).shape)
    
    # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    
    
    # fill the missing in (VIP , TRansported , CryoSleep) by False
    df[['CryoSleep','VIP','Transported']] = df[['CryoSleep','VIP','Transported']].fillna(False)
     
    #  fill the missing value in column Age by meadin()
    df['Age'] = df['Age'].fillna(df['Age'].median())
   
   
    # fill the missing value in column spending by fillna(0) 
    cols = ['RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']
    df[cols] = df[cols].fillna(0)
    # make anther column for total spending by sum the spending columns
    df['Total_spending'] = df[cols].sum(axis=1)
    return df